"""add asset_snapshots

Revision ID: 0c2552388afd
Revises: c013e455162f
Create Date: 2026-07-22 18:30:10.105117
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0c2552388afd'
down_revision: str | None = 'c013e455162f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=0), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_snapshots_month'), 'asset_snapshots', ['month'], unique=False)
    op.create_index(op.f('ix_asset_snapshots_year'), 'asset_snapshots', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_snapshots_year'), table_name='asset_snapshots')
    op.drop_index(op.f('ix_asset_snapshots_month'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ###
